apiVersion: apps/v1
kind: Deployment
metadata:
  name: whiteboard-backend-deployment
  labels:
    app: whiteboard-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: whiteboard-backend-deployment
  template:
    metadata:
      labels:
        deployment: whiteboard-backend-deployment
    spec:
      containers:
        - name: whiteboard-backend
          image: ghostrider9972/whiteboard-server:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
            - containerPort: 5701

---
apiVersion: v1
kind: Service
metadata:
  name: whiteboard-backend-lb
  labels:
    app: whiteboard-backend
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10
  ports:
    - name: socket-connection
      port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    deployment: whiteboard-backend-deployment
