version: "3.9"
services:
  web1:
    image: whiteboard-server:latest
    environment:
      - PORT=9092
    ports:
      - "9092:9092"
  web2:
    image: whiteboard-server:latest
    environment:
      - PORT=9093
    ports:
      - "9093:9093"
  web3:
    image: whiteboard-server:latest
    environment:
      - PORT=9094
    ports:
      - "9094:9094"

networks:
  network1: