apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: WhiteBoard-Cluster
  region: eu-west-2

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: cluster-autoscaler
        namespace: kube-system
      wellKnownPolicies:
        autoScaler: true
      roleName: eksctl-cluster-autoscaler
      roleOnly: true

managedNodeGroups:
  - name: Node-Group
    iam:
      withAddonPolicies:
        autoScaler: true
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/WhiteBoard-Cluster: "owned"
    labels:
      worker: default
    instanceType: t2.small
    desiredCapacity: 3
    minSize: 3
    maxSize: 5
availabilityZones: ["eu-west-2a", "eu-west-2b"]
